name: "Auto assign PR author"

on:
  pull_request_target:
    types: [opened, reopened]

jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - name: Use auto-author-assign package
        uses: toshimaru/auto-author-assign@v1.4.0
